package it.eng.idsa.streamer.util;


public enum RejectionMessageType {
	
	RESULT_MESSAGE,
	REJECTION_MESSAGE_COMMON,
	REJECTION_TOKEN,
	REJECTION_MESSAGE_LOCAL_ISSUES,
	REJECTION_TOKEN_LOCAL_ISSUES,
	REJECTION_COMMUNICATION_LOCAL_ISSUES
	
}
